name: PR automation

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  auto-fill-pr-info:
    runs-on: ubuntu-latest
    steps:
      - name: Auto assign author
        uses: toshimaru/auto-author-assign@v2.0.0

      - name: Update PR title
        uses: tzkhan/pr-update-action@v2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          base-branch-regex: '[a-z\d-_.\\/]+'
          head-branch-regex: '[a-z\d-_.\\/]+'
          title-template: ${{ github.head_ref || github.ref_name }}
          title-update-action: replace

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get commit info
        run: |
          echo "FIRST_COMMIT=$(git log --format=%H origin/${{ github.base_ref }}..origin/${{ github.head_ref }} | tail -1)" >> $GITHUB_ENV
          echo "LAST_COMMIT=$(git log --format=%H -n 1 origin/${{ github.head_ref }})" >> $GITHUB_ENV
          echo "GITHUB_COMMITS_FORMATTED=$(git log --pretty=format:'|%s|%b%-C|' ${{ env.FIRST_COMMIT }}...${{ env.LAST_COMMIT }}^)" >> $GITHUB_ENV
          echo $GITHUB_COMMITS_FORMATTED
